name: Malinda Dilhara
url: https://maldil.github.io
description: “Before software can be reusable it first has to be usable.” – Ralph Johnson

permalink: /:year/:month/:day/:title/
paginate: 10

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
